use std::io::{Read, Seek, Write};
use std::path::{Path, PathBuf};
use thiserror::Error;
use walkdir::WalkDir;
use zip::write::SimpleFileOptions;
use zip::ZipWriter;

#[derive(Error, Debug)]
pub enum PharError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Zip error: {0}")]
    Zip(#[from] zip::result::ZipError),
    #[error("Path error: {0}")]
    Path(String),
}

pub struct PharBuilder<W: Write + Seek> {
    writer: ZipWriter<W>,
    #[allow(dead_code)]
    base_path: PathBuf,
    compression_method: zip::CompressionMethod,
}

impl<W: Write + Seek> PharBuilder<W> {
    pub fn into_inner(self) -> W {
        self.writer.finish().unwrap()
    }

    pub fn set_compression(&mut self, method: zip::CompressionMethod) {
        self.compression_method = method;
    }
}

pub fn create_phar_from_directory(
    dir: &Path,
    output: &Path,
    exclude_patterns: &[String],
    entry_point: &str,
) -> Result<PathBuf, PharError> {
    let file = std::fs::File::create(output)?;
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    for entry in WalkDir::new(dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        let relative = path.strip_prefix(dir).unwrap_or(path);
        let relative_str = relative.to_string_lossy().replace('\\', "/");

        if relative_str == ".git" || relative_str.starts_with(".git/") {
            continue;
        }

        if exclude_patterns.iter().any(|p| {
            if p.ends_with('/') {
                relative_str.starts_with(p.trim_end_matches('/'))
            } else {
                relative_str == *p || relative_str.ends_with(p)
            }
        }) {
            continue;
        }

        if path.is_file() {
            let mut file_content = Vec::new();
            std::fs::File::open(path)?.read_to_end(&mut file_content)?;
            zip.start_file(&relative_str, options)?;
            zip.write_all(&file_content)?;
        } else if path.is_dir() && !relative_str.is_empty() {
            let dir_name = format!("{}/", relative_str);
            zip.add_directory(&dir_name, options)?;
        }
    }

    let default_stub = generate_stub(entry_point);
    zip.start_file("__stub__.php", options)?;
    zip.write_all(default_stub.as_bytes())?;

    zip.finish()?;
    Ok(output.to_path_buf())
}

fn generate_stub(entry_point: &str) -> String {
    format!(
        r#"<?php
/**
 * CleanServe PHAR Stub
 * Auto-generated by CleanServe Bundle
 */

Phar::mapPhar('app.phar');

$entry = '{entry}';
$script = __DIR__ . '/{entry}';

if (file_exists($script)) {{
    require_once $script;
}} else {{
    echo "Entry point not found: $entry\n";
    exit(1);
}}

__HALT_COMPILER();
"#,
        entry = entry_point
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stub_generation() {
        let stub = generate_stub("public/index.php");
        assert!(stub.contains("public/index.php"));
        assert!(stub.contains("Phar::mapPhar"));
    }
}
