use crate::composer::{ComposerError, ComposerJson};
use regex::Regex;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use thiserror::Error;
use walkdir::WalkDir;

#[derive(Error, Debug)]
pub enum PreloadError {
    #[error("Composer error: {0}")]
    Composer(#[from] ComposerError),
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),
    #[error("Regex error: {0}")]
    Regex(#[from] regex::Error),
}

pub struct PreloadGenerator {
    project_root: PathBuf,
    composer: ComposerJson,
    entry_points: Vec<PathBuf>,
    exclude_patterns: Vec<Regex>,
}

impl PreloadGenerator {
    pub fn from_project(project_root: impl AsRef<Path>) -> Result<Self, PreloadError> {
        let composer = ComposerJson::from_project(&project_root)?;
        let exclude_patterns = Self::default_exclude_patterns();

        Ok(Self {
            project_root: project_root.as_ref().to_path_buf(),
            composer,
            entry_points: vec![
                PathBuf::from("index.php"),
                PathBuf::from("public/index.php"),
                PathBuf::from("artisan"),
                PathBuf::from("cli/index.php"),
                PathBuf::from("bin/console"),
            ],
            exclude_patterns,
        })
    }

    fn default_exclude_patterns() -> Vec<Regex> {
        vec![
            Regex::new(r"(?m)(^|/)tests?/").unwrap(),
            Regex::new(r"\.Test\.php$").unwrap(),
            Regex::new(r"(^|/)var/").unwrap(),
            Regex::new(r"(^|/)storage/").unwrap(),
            Regex::new(r"(^|/)vendor/.*/(test|spec|demo|example)/").unwrap(),
            Regex::new(r"\.phpunit\.").unwrap(),
            Regex::new(r"\.bak$").unwrap(),
            Regex::new(r"\.backup$").unwrap(),
        ]
    }

    pub fn with_excludes(mut self, excludes: Vec<&str>) -> Result<Self, PreloadError> {
        for pattern in excludes {
            self.exclude_patterns.push(Regex::new(pattern)?);
        }
        Ok(self)
    }

    pub fn generate_script(&self) -> Result<String, PreloadError> {
        let files = self.collect_files()?;
        Ok(self.render_script(&files))
    }

    pub fn collect_files(&self) -> Result<Vec<String>, PreloadError> {
        let mut files = Vec::new();
        let mut seen = HashSet::new();

        let namespaces = self.composer.get_psr4_namespaces();
        for (_prefix, path) in &namespaces {
            let full_path = self.project_root.join(path);
            self.walk_and_add(&full_path, &mut files, &mut seen)?;
        }

        let extra_paths = self.composer.get_extra_preload_paths();
        for path in &extra_paths {
            let full_path = self.project_root.join(path);
            self.walk_and_add(&full_path, &mut files, &mut seen)?;
        }

        files.sort();
        files.dedup();
        Ok(files)
    }

    fn walk_and_add(
        &self,
        dir: &Path,
        files: &mut Vec<String>,
        seen: &mut HashSet<String>,
    ) -> Result<(), PreloadError> {
        if !dir.exists() {
            return Ok(());
        }

        for entry in WalkDir::new(dir).into_iter().filter_map(|e| e.ok()) {
            let path = entry.path();

            if !path.is_file() || path.extension().map_or(true, |e| e != "php") {
                continue;
            }

            let path_str = path.to_string_lossy().to_string();

            if self.exclude_patterns.iter().any(|p| p.is_match(&path_str)) {
                continue;
            }

            if seen.contains(&path_str) {
                continue;
            }
            seen.insert(path_str.clone());

            if let Ok(relative) = path.strip_prefix(&self.project_root) {
                files.push(normalize_path(relative));
            }
        }

        Ok(())
    }

    fn render_script(&self, files: &[String]) -> String {
        let timestamp = chrono::Utc::now().to_rfc3339();
        let mut output = format!(
            r#"<?php
/**
 * Auto-generated by CleanServe Preload Generator
 * Generated at: {}
 * Project: {}
 */

if (!function_exists('opcache_compile_file')) {{
    echo "OpCache not available, skipping preload\n";
    return;
}}

// Files to preload ({})
$files = [
"#,
            timestamp,
            self.composer.name.as_deref().unwrap_or("unknown"),
            files.len()
        );

        for file in files {
            output.push_str(&format!("    '{}',\n", file.replace('\\', "/")));
        }

        output.push_str(
            r#"];

// Preload files
$preloaded = 0;
$failed = 0;
$errors = [];

foreach ($files as $file) {
    $path = __DIR__ . '/' . $file;
    if (file_exists($path) && is_readable($path)) {
        if (!opcache_compile_file($path)) {
            $failed++;
            $errors[] = $file;
        } else {
            $preloaded++;
        }
    }
}

echo "Preloaded {$preloaded} files";
if ($failed > 0) {
    echo " ({$failed} failed)";
}
echo "\n";
"#,
        );

        output
    }

    pub fn save_script(&self, output_path: impl AsRef<Path>) -> Result<(), PreloadError> {
        let script = self.generate_script()?;
        std::fs::write(output_path, script)?;
        Ok(())
    }
}

fn normalize_path(path: &Path) -> String {
    let mut result = PathBuf::new();
    for component in path.components() {
        match component {
            std::path::Component::Normal(s) => {
                if result.to_string_lossy() != "" {
                    result.push(s);
                } else {
                    result = PathBuf::from(s);
                }
            }
            _ => {}
        }
    }
    result.to_string_lossy().to_string().replace('\\', "/")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn create_test_project() -> TempDir {
        let dir = TempDir::new().unwrap();

        std::fs::create_dir_all(dir.path().join("src")).unwrap();
        std::fs::create_dir_all(dir.path().join("vendor/test/pkg")).unwrap();

        std::fs::write(
            dir.path().join("composer.json"),
            r#"{
                "name": "test/project",
                "autoload": {
                    "psr-4": {
                        "App\\": "src/"
                    }
                }
            }"#,
        )
        .unwrap();

        std::fs::write(
            dir.path().join("src/Controller.php"),
            "<?php\nclass Controller {}",
        )
        .unwrap();
        std::fs::write(dir.path().join("src/Model.php"), "<?php\nclass Model {}").unwrap();
        std::fs::write(
            dir.path().join("vendor/test/pkg/Lib.php"),
            "<?php\nclass Lib {}",
        )
        .unwrap();

        dir
    }

    #[test]
    fn test_collect_files() {
        let dir = create_test_project();
        let generator = PreloadGenerator::from_project(dir.path()).unwrap();
        let files = generator.collect_files().unwrap();

        assert!(files.contains(&"src/Controller.php".to_string()));
        assert!(files.contains(&"src/Model.php".to_string()));
    }

    #[test]
    fn test_generate_script() {
        let dir = create_test_project();
        let generator = PreloadGenerator::from_project(dir.path()).unwrap();
        let script = generator.generate_script().unwrap();

        assert!(script.contains("<?php"));
        assert!(script.contains("opcache_compile_file"));
        assert!(script.contains("src/Controller.php"));
    }

    #[test]
    fn test_exclude_patterns() {
        let dir = create_test_project();

        std::fs::create_dir_all(dir.path().join("tests")).unwrap();
        std::fs::write(dir.path().join("tests/Test.php"), "<?php\nclass Test {}").unwrap();

        let generator = PreloadGenerator::from_project(dir.path())
            .unwrap()
            .with_excludes(vec![r"(^|/)tests/"])
            .unwrap();

        let files = generator.collect_files().unwrap();
        assert!(!files.iter().any(|f| f.contains("tests")));
    }
}
