use crate::parser::EnvParser;
use std::path::Path;

pub struct PhpGenerator {
    parser: EnvParser,
    namespace: Option<String>,
}

impl PhpGenerator {
    pub fn new(parser: EnvParser) -> Self {
        Self {
            parser,
            namespace: None,
        }
    }

    pub fn with_namespace(mut self, namespace: &str) -> Self {
        self.namespace = Some(namespace.to_string());
        self.namespace = Some(namespace.to_string());
        self
    }

    pub fn generate(&self) -> String {
        let mut output = String::new();

        output.push_str(
            r#"<?php
/**
 * Auto-generated by CleanServe Environment Inliner
 * 
 * This file contains environment variables as PHP constants.
 * For performance, use these constants instead of getenv() or $_ENV.
 */

if (!defined('CLEANSERVE_ENV_INLINED')) {
    define('CLEANSERVE_ENV_INLINED', true);
}

// Environment configuration
"#,
        );

        for entry in self.parser.entries() {
            if entry.key.is_empty() {
                continue;
            }

            if let Some(ref comment) = entry.comment {
                output.push_str(&format!("// {}\n", comment));
            }

            let const_name = self.to_const_name(&entry.key);
            let escaped_value = self.escape_php_string(&entry.value);

            if let Some(ref ns) = self.namespace {
                output.push_str(&format!(
                    "define('{}\\{}', '{}');\n",
                    ns, const_name, escaped_value
                ));
            } else {
                output.push_str(&format!("define('{}', '{}');\n", const_name, escaped_value));
            }
        }

        output.push_str(
            r#"

// env() helper function for fallback
if (!function_exists('env')) {
    /**
     * Get environment variable with fallback.
     */
    function env(string $key, mixed $default = null): mixed
    {
        if (defined($key)) {
            $value = constant($key);
            return $value === 'true' ? true 
                 : $value === 'false' ? false 
                 : $value === 'null' ? null 
                 : $value;
        }
        $env = getenv($key);
        return $env !== false ? $env : $default;
    }
}

// $_ENV compatibility
if (!function_exists('_env')) {
    /**
     * Get $_ENV variable with inlined fallback.
     */
    function _env(string $key, mixed $default = null): mixed
    {
        return $_ENV[$key] ?? env($key, $default);
    }
}
"#,
        );

        output
    }

    pub fn generate_bootstrap(&self, bootstrap_path: &Path) -> std::io::Result<String> {
        let relative = bootstrap_path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("env.php");

        let env_file_name = if relative.ends_with(".php") {
            relative.trim_end_matches(".php").to_string() + ".php"
        } else {
            relative.to_string()
        };

        let output = format!(
            r#"<?php
/**
 * Environment Bootstrap
 * 
 * Include this file to load environment variables.
 * Auto-generated by CleanServe.
 */

$__envFile = __DIR__ . '/{}';
if (file_exists($__envFile)) {{
    require_once $__envFile;
}}
"#,
            env_file_name
        );

        Ok(output)
    }

    fn to_const_name(&self, key: &str) -> String {
        let mut result = key
            .replace('.', "_")
            .replace('-', "_")
            .replace(' ', "_")
            .to_uppercase();

        if result.chars().next().map_or(false, |c| c.is_ascii_digit()) {
            result = format!("_{}", result);
        }

        result
    }

    fn escape_php_string(&self, s: &str) -> String {
        s.replace('\\', "\\\\")
            .replace('\'', "\\'")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t")
            .replace('$', "\\$")
    }

    pub fn save(&self, output_path: impl AsRef<Path>) -> std::io::Result<()> {
        std::fs::write(output_path, self.generate())
    }
}

impl From<EnvParser> for PhpGenerator {
    fn from(parser: EnvParser) -> Self {
        Self::new(parser)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_generation() {
        let parser = EnvParser::from_str("APP_NAME=MyApp\nAPP_ENV=production");
        let generator = PhpGenerator::new(parser);
        let php = generator.generate();

        assert!(php.contains("define('APP_NAME', 'MyApp')"));
        assert!(php.contains("define('APP_ENV', 'production')"));
        assert!(php.contains("function env("));
    }

    #[test]
    fn test_dotted_key_conversion() {
        let parser = EnvParser::from_str("DATABASE.HOST=localhost");
        let generator = PhpGenerator::new(parser);
        let php = generator.generate();

        assert!(php.contains("define('DATABASE_HOST', 'localhost')"));
    }

    #[test]
    fn test_numeric_prefix() {
        let parser = EnvParser::from_str("123_NAME=test");
        let generator = PhpGenerator::new(parser);
        let php = generator.generate();

        assert!(php.contains("define('_123_NAME', 'test')"));
    }

    #[test]
    fn test_escape_special_chars() {
        let parser = EnvParser::from_str("API_KEY=pass$word");
        let generator = PhpGenerator::new(parser);
        let php = generator.generate();

        assert!(php.contains(r"\$"));
    }

    #[test]
    fn test_namespace() {
        let parser = EnvParser::from_str("KEY=value");
        let generator = PhpGenerator::new(parser).with_namespace("App\\Config");
        let php = generator.generate();

        assert!(php.contains(r"define('App\Config\KEY'"));
    }
}
